services:
  metaport-backend:
    build:
      context: ./backend
      network: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    container_name: metaport-backend
    restart: unless-stopped
    ports:
      - "8025:8025"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/docs:/app/docs
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /mnt:/host_mnt:ro
      - /media:/host_media:ro
      - /proc/mounts:/host_proc_mounts:ro
    networks:
      - sdilena_databazova_sit

  metaport-frontend:
    build:
      context: ./frontend
      network: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    container_name: metaport-frontend
    restart: unless-stopped
    ports:
      - "85:80"
    networks:
      - sdilena_databazova_sit

  metaport-db:
    image: postgres:15
    container_name: metaport-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metaportdb
    networks:
      - sdilena_databazova_sit

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: metaport-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - ./backend/.env
    networks:
      - sdilena_databazova_sit

networks:
  sdilena_databazova_sit:
    external: true
