services:
  metaport-backend:
    build:
      context: ./backend
      network: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    container_name: metaport-backend
    restart: unless-stopped
    expose:
      - "8025"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/docs:/app/docs
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket

  metaport-frontend:
    build:
      context: ./frontend
      network: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    container_name: metaport-frontend
    restart: unless-stopped
    expose:
      - "85"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: metaport-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - ./backend/.env